import type {
  Investigation,
  Case,
  Evidence,
  Entity,
  TimelineEvent,
  IntelligenceFeed,
  DashboardStats,
  User,
} from "./types";

export const currentUser: User = {
  id: "user-001",
  name: "Alex Morgan",
  email: "alex.morgan@spyford.io",
  role: "analyst",
  avatar: undefined,
  department: "Cyber Intelligence",
  lastActive: new Date().toISOString(),
};

export const investigations: Investigation[] = [
  {
    id: "inv-001",
    title: "Operation Dark Horizon",
    description: "Multi-vector APT campaign targeting financial infrastructure across APAC region",
    status: "active",
    leadAnalyst: "Alex Morgan",
    team: ["Sarah Chen", "Marcus Webb", "Priya Sharma"],
    createdAt: "2026-05-01T08:00:00Z",
    updatedAt: "2026-05-29T14:30:00Z",
    caseCount: 12,
    evidenceCount: 847,
    tags: ["APT", "Financial", "APAC", "Critical"],
  },
  {
    id: "inv-002",
    title: "Phantom Network Intrusion",
    description: "Suspected state-sponsored intrusion into government contractor networks",
    status: "active",
    leadAnalyst: "Marcus Webb",
    team: ["Alex Morgan", "James Liu"],
    createdAt: "2026-05-15T10:00:00Z",
    updatedAt: "2026-05-28T16:45:00Z",
    caseCount: 8,
    evidenceCount: 324,
    tags: ["State-Sponsored", "Government", "High Priority"],
  },
  {
    id: "inv-003",
    title: "Supply Chain Compromise",
    description: "Investigation into compromised software supply chain affecting multiple vendors",
    status: "pending",
    leadAnalyst: "Sarah Chen",
    team: ["Priya Sharma", "David Kim"],
    createdAt: "2026-05-20T12:00:00Z",
    updatedAt: "2026-05-27T09:15:00Z",
    caseCount: 5,
    evidenceCount: 156,
    tags: ["Supply Chain", "Software", "Vendors"],
  },
  {
    id: "inv-004",
    title: "Insider Threat Assessment",
    description: "Behavioral analysis of potential insider threat indicators",
    status: "active",
    leadAnalyst: "Priya Sharma",
    team: ["Alex Morgan"],
    createdAt: "2026-05-22T14:00:00Z",
    updatedAt: "2026-05-29T11:00:00Z",
    caseCount: 3,
    evidenceCount: 89,
    tags: ["Insider Threat", "Behavioral", "Confidential"],
  },
  {
    id: "inv-005",
    title: "Ransomware Attribution",
    description: "Attribution analysis for emerging ransomware group targeting healthcare",
    status: "closed",
    leadAnalyst: "James Liu",
    team: ["Marcus Webb", "Sarah Chen"],
    createdAt: "2026-04-10T08:00:00Z",
    updatedAt: "2026-05-15T17:30:00Z",
    caseCount: 7,
    evidenceCount: 412,
    tags: ["Ransomware", "Healthcare", "Attribution"],
  },
];

export const cases: Case[] = [
  {
    id: "case-001",
    investigationId: "inv-001",
    title: "Initial Access Vector Analysis",
    description: "Analyze the initial compromise vector used in the Dark Horizon campaign",
    status: "in-progress",
    priority: "critical",
    assignee: "Alex Morgan",
    createdAt: "2026-05-02T09:00:00Z",
    updatedAt: "2026-05-29T10:00:00Z",
    dueDate: "2026-06-01T00:00:00Z",
    evidenceIds: ["ev-001", "ev-002", "ev-003"],
    entityIds: ["ent-001", "ent-002"],
    notes: "Focus on spear-phishing artifacts and initial payload delivery mechanism",
  },
  {
    id: "case-002",
    investigationId: "inv-001",
    title: "C2 Infrastructure Mapping",
    description: "Map command and control infrastructure used by threat actor",
    status: "open",
    priority: "high",
    assignee: "Sarah Chen",
    createdAt: "2026-05-05T11:00:00Z",
    updatedAt: "2026-05-28T14:00:00Z",
    dueDate: "2026-06-05T00:00:00Z",
    evidenceIds: ["ev-004", "ev-005"],
    entityIds: ["ent-003", "ent-004"],
    notes: "Correlate with known APT infrastructure patterns",
  },
  {
    id: "case-003",
    investigationId: "inv-001",
    title: "Lateral Movement Analysis",
    description: "Document lateral movement techniques observed in compromised networks",
    status: "review",
    priority: "high",
    assignee: "Marcus Webb",
    createdAt: "2026-05-08T08:30:00Z",
    updatedAt: "2026-05-27T16:00:00Z",
    evidenceIds: ["ev-006", "ev-007", "ev-008"],
    entityIds: ["ent-005"],
    notes: "Review PsExec usage and credential harvesting artifacts",
  },
  {
    id: "case-004",
    investigationId: "inv-002",
    title: "Network Traffic Analysis",
    description: "Analyze captured network traffic for indicators of compromise",
    status: "in-progress",
    priority: "critical",
    assignee: "James Liu",
    createdAt: "2026-05-16T10:00:00Z",
    updatedAt: "2026-05-29T09:00:00Z",
    dueDate: "2026-05-31T00:00:00Z",
    evidenceIds: ["ev-009", "ev-010"],
    entityIds: ["ent-006"],
    notes: "Focus on encrypted DNS exfiltration patterns",
  },
  {
    id: "case-005",
    investigationId: "inv-002",
    title: "Malware Reverse Engineering",
    description: "Reverse engineer captured malware samples",
    status: "open",
    priority: "high",
    assignee: "Alex Morgan",
    createdAt: "2026-05-18T14:00:00Z",
    updatedAt: "2026-05-26T11:00:00Z",
    evidenceIds: ["ev-011", "ev-012"],
    entityIds: [],
    notes: "Custom loader with anti-analysis techniques detected",
  },
];

export const evidence: Evidence[] = [
  {
    id: "ev-001",
    caseId: "case-001",
    name: "phishing_email_sample.eml",
    type: "document",
    description: "Original spear-phishing email with malicious attachment",
    source: "Email Gateway Logs",
    hash: "sha256:a7f3d8c2e1b9f4a6d5c8e7b2f1a9d4c6e8b3f5a2d7c1e9b4f6a8d2c5e7b1f3a9",
    fileSize: 245760,
    mimeType: "message/rfc822",
    uploadedBy: "Sarah Chen",
    uploadedAt: "2026-05-02T10:30:00Z",
    chainOfCustody: [
      { id: "coc-001", action: "Collected", performedBy: "Sarah Chen", timestamp: "2026-05-02T10:30:00Z" },
      { id: "coc-002", action: "Analyzed", performedBy: "Alex Morgan", timestamp: "2026-05-03T14:00:00Z" },
    ],
    tags: ["phishing", "initial-access", "email"],
    metadata: { sender: "hr-updates@corp-notifications.com", recipients: 47 },
  },
  {
    id: "ev-002",
    caseId: "case-001",
    name: "malicious_macro.docm",
    type: "document",
    description: "Word document with embedded malicious macro",
    source: "Endpoint Detection",
    hash: "sha256:b8f4e9d3c2a1f5b7e6d4c9a2f8b1e7d3c6a9f2b5e8d1c4a7f3b6e9d2c5a8f1b4",
    fileSize: 89120,
    mimeType: "application/vnd.ms-word.document.macroEnabled.12",
    uploadedBy: "Alex Morgan",
    uploadedAt: "2026-05-02T11:45:00Z",
    chainOfCustody: [
      { id: "coc-003", action: "Extracted", performedBy: "Alex Morgan", timestamp: "2026-05-02T11:45:00Z" },
      { id: "coc-004", action: "Detonated in Sandbox", performedBy: "Marcus Webb", timestamp: "2026-05-02T15:00:00Z" },
    ],
    tags: ["malware", "macro", "dropper"],
    metadata: { author: "Unknown", createDate: "2026-04-28" },
  },
  {
    id: "ev-003",
    caseId: "case-001",
    name: "network_capture_001.pcap",
    type: "digital",
    description: "Network capture during initial infection",
    source: "Network TAP",
    hash: "sha256:c9f5e0d4c3b2f6a8e7d5c0a3f9b2e8d4c7a0f3b6e9d2c5a8f1b4e7d0c3a6f9b2",
    fileSize: 15728640,
    mimeType: "application/vnd.tcpdump.pcap",
    uploadedBy: "James Liu",
    uploadedAt: "2026-05-03T08:00:00Z",
    chainOfCustody: [
      { id: "coc-005", action: "Captured", performedBy: "James Liu", timestamp: "2026-05-03T08:00:00Z" },
    ],
    tags: ["network", "pcap", "c2-traffic"],
    metadata: { duration: "4h 23m", packetCount: 2847563 },
  },
  {
    id: "ev-004",
    caseId: "case-002",
    name: "c2_server_screenshot.png",
    type: "image",
    description: "Screenshot of identified C2 server admin panel",
    source: "OSINT Collection",
    fileSize: 524288,
    mimeType: "image/png",
    uploadedBy: "Sarah Chen",
    uploadedAt: "2026-05-06T16:00:00Z",
    chainOfCustody: [
      { id: "coc-006", action: "Captured", performedBy: "Sarah Chen", timestamp: "2026-05-06T16:00:00Z" },
    ],
    tags: ["c2", "infrastructure", "screenshot"],
    metadata: { resolution: "1920x1080", captured: "2026-05-06" },
  },
  {
    id: "ev-005",
    caseId: "case-002",
    name: "domain_registration_data.json",
    type: "digital",
    description: "WHOIS and registration data for C2 domains",
    source: "Domain Intelligence",
    fileSize: 45056,
    mimeType: "application/json",
    uploadedBy: "Sarah Chen",
    uploadedAt: "2026-05-07T09:30:00Z",
    chainOfCustody: [
      { id: "coc-007", action: "Collected", performedBy: "Sarah Chen", timestamp: "2026-05-07T09:30:00Z" },
    ],
    tags: ["domains", "whois", "registration"],
    metadata: { domainCount: 23, registrars: ["NameCheap", "GoDaddy", "Njalla"] },
  },
];

export const entities: Entity[] = [
  {
    id: "ent-001",
    type: "organization",
    name: "APT-X47",
    aliases: ["DarkHorizon", "ShadowBear", "TempestGroup"],
    description: "Suspected state-sponsored threat actor group targeting financial institutions",
    attributes: {
      origin: "Eastern Europe",
      firstSeen: "2024-03",
      motivation: "Financial Espionage",
      sophistication: "High",
    },
    relationships: [
      { id: "rel-001", targetEntityId: "ent-002", relationshipType: "operates", confidence: 85, source: "Internal Analysis" },
    ],
    linkedCases: ["case-001", "case-002"],
    linkedEvidence: ["ev-001", "ev-002"],
    createdAt: "2026-05-02T12:00:00Z",
    updatedAt: "2026-05-28T10:00:00Z",
    riskScore: 94,
    tags: ["APT", "State-Sponsored", "Financial"],
  },
  {
    id: "ent-002",
    type: "device",
    name: "C2 Server Alpha",
    aliases: [],
    description: "Primary command and control server",
    attributes: {
      ip: "185.XXX.XXX.42",
      hosting: "BulletProof Hosting",
      firstSeen: "2026-04-15",
      lastSeen: "2026-05-29",
    },
    relationships: [],
    linkedCases: ["case-002"],
    linkedEvidence: ["ev-004", "ev-005"],
    createdAt: "2026-05-06T14:00:00Z",
    updatedAt: "2026-05-29T08:00:00Z",
    riskScore: 88,
    tags: ["C2", "Infrastructure", "Active"],
  },
  {
    id: "ent-003",
    type: "person",
    name: "UNKNOWN-01",
    aliases: ["darkadmin", "x47_operator"],
    description: "Suspected operator associated with APT-X47 infrastructure",
    attributes: {
      language: "Russian",
      timezone: "UTC+3",
      activityPattern: "Business Hours (Moscow)",
    },
    relationships: [
      { id: "rel-002", targetEntityId: "ent-001", relationshipType: "member_of", confidence: 72, source: "Behavioral Analysis" },
    ],
    linkedCases: ["case-001"],
    linkedEvidence: [],
    createdAt: "2026-05-10T11:00:00Z",
    updatedAt: "2026-05-25T15:00:00Z",
    riskScore: 76,
    tags: ["Operator", "Person of Interest"],
  },
  {
    id: "ent-004",
    type: "account",
    name: "crypto_wallet_001",
    aliases: [],
    description: "Cryptocurrency wallet used for ransom payments",
    attributes: {
      type: "Bitcoin",
      address: "bc1q...redacted",
      totalReceived: "47.3 BTC",
      transactionCount: 156,
    },
    relationships: [
      { id: "rel-003", targetEntityId: "ent-001", relationshipType: "controlled_by", confidence: 68, source: "Blockchain Analysis" },
    ],
    linkedCases: [],
    linkedEvidence: [],
    createdAt: "2026-05-12T09:00:00Z",
    updatedAt: "2026-05-28T14:00:00Z",
    riskScore: 82,
    tags: ["Cryptocurrency", "Financial", "Bitcoin"],
  },
  {
    id: "ent-005",
    type: "location",
    name: "Hosting Facility - Eastern Europe",
    aliases: [],
    description: "Suspected bulletproof hosting facility",
    attributes: {
      country: "Moldova",
      city: "Chisinau",
      provider: "Unknown",
    },
    relationships: [
      { id: "rel-004", targetEntityId: "ent-002", relationshipType: "hosts", confidence: 91, source: "Infrastructure Analysis" },
    ],
    linkedCases: ["case-002"],
    linkedEvidence: ["ev-005"],
    createdAt: "2026-05-08T10:00:00Z",
    updatedAt: "2026-05-20T12:00:00Z",
    riskScore: 65,
    tags: ["Infrastructure", "Hosting", "Location"],
  },
];

export const timelineEvents: TimelineEvent[] = [
  {
    id: "tl-001",
    timestamp: "2026-05-29T14:30:00Z",
    title: "New Evidence Uploaded",
    description: "Network capture file added to Case #001",
    type: "evidence",
    relatedIds: { caseId: "case-001", evidenceId: "ev-003" },
    actor: "James Liu",
  },
  {
    id: "tl-002",
    timestamp: "2026-05-29T12:15:00Z",
    title: "Case Status Updated",
    description: "Lateral Movement Analysis moved to Review status",
    type: "case",
    relatedIds: { caseId: "case-003", investigationId: "inv-001" },
    actor: "Marcus Webb",
  },
  {
    id: "tl-003",
    timestamp: "2026-05-29T10:00:00Z",
    title: "Critical Alert: New IOC Detected",
    description: "New IP address associated with APT-X47 infrastructure identified",
    type: "intelligence",
    severity: "critical",
    relatedIds: { investigationId: "inv-001" },
    actor: "System",
  },
  {
    id: "tl-004",
    timestamp: "2026-05-29T08:45:00Z",
    title: "Entity Relationship Added",
    description: "New connection established between APT-X47 and crypto wallet",
    type: "entity",
    relatedIds: {},
    actor: "Sarah Chen",
  },
  {
    id: "tl-005",
    timestamp: "2026-05-28T16:45:00Z",
    title: "Investigation Updated",
    description: "Phantom Network Intrusion investigation notes updated",
    type: "investigation",
    relatedIds: { investigationId: "inv-002" },
    actor: "Marcus Webb",
  },
  {
    id: "tl-006",
    timestamp: "2026-05-28T14:00:00Z",
    title: "High Priority Alert",
    description: "Threat intelligence match for monitored indicators",
    type: "intelligence",
    severity: "high",
    relatedIds: {},
    actor: "System",
  },
];

export const intelligenceFeeds: IntelligenceFeed[] = [
  {
    id: "intel-001",
    name: "APT Activity Report",
    type: "report",
    source: "Internal Analysis",
    severity: "critical",
    title: "APT-X47 Campaign Expansion Detected",
    summary: "New infrastructure and TTPs identified suggesting campaign expansion to new geographic regions",
    indicators: ["185.XXX.XXX.42", "darkcdn.example.com", "update-service.example.net"],
    publishedAt: "2026-05-29T06:00:00Z",
    tags: ["APT", "Campaign", "Expansion"],
  },
  {
    id: "intel-002",
    name: "Vulnerability Alert",
    type: "vulnerability",
    source: "CVE Database",
    severity: "high",
    title: "Critical RCE in Enterprise Software",
    summary: "Remote code execution vulnerability discovered in widely deployed enterprise software",
    indicators: ["CVE-2026-XXXX"],
    publishedAt: "2026-05-28T18:00:00Z",
    tags: ["Vulnerability", "RCE", "Enterprise"],
  },
  {
    id: "intel-003",
    name: "IOC Feed Update",
    type: "indicator",
    source: "Threat Intelligence Platform",
    severity: "medium",
    title: "New Malware Hashes Published",
    summary: "23 new malware sample hashes associated with ransomware operations",
    indicators: ["sha256:a1b2c3...", "sha256:d4e5f6...", "sha256:g7h8i9..."],
    publishedAt: "2026-05-28T12:00:00Z",
    tags: ["IOC", "Malware", "Ransomware"],
  },
  {
    id: "intel-004",
    name: "Threat Landscape Brief",
    type: "report",
    source: "External Partner",
    severity: "medium",
    title: "Weekly Threat Landscape Summary",
    summary: "Overview of significant cyber threat activity observed in the past week",
    indicators: [],
    publishedAt: "2026-05-27T09:00:00Z",
    tags: ["Weekly", "Summary", "Landscape"],
  },
];

export const dashboardStats: DashboardStats = {
  activeInvestigations: 4,
  openCases: 18,
  pendingEvidence: 127,
  criticalAlerts: 3,
  recentActivity: [
    { id: "act-001", type: "evidence", message: "New evidence uploaded to Dark Horizon", timestamp: "2026-05-29T14:30:00Z", actor: "James Liu", link: "/evidence/ev-003" },
    { id: "act-002", type: "case", message: "Case status changed to Review", timestamp: "2026-05-29T12:15:00Z", actor: "Marcus Webb", link: "/cases/case-003" },
    { id: "act-003", type: "alert", message: "Critical IOC detected in network traffic", timestamp: "2026-05-29T10:00:00Z", actor: "System", link: "/intelligence" },
    { id: "act-004", type: "entity", message: "New entity relationship mapped", timestamp: "2026-05-29T08:45:00Z", actor: "Sarah Chen", link: "/entities" },
    { id: "act-005", type: "investigation", message: "Investigation notes updated", timestamp: "2026-05-28T16:45:00Z", actor: "Marcus Webb", link: "/investigations/inv-002" },
  ],
};
